site_name: Evernode
docs_dir: src
site_dir: docs
nav:
    - Registry: registry/index.md
    - Hosts: hosts/index.md
    - Users: users/index.md
    - Purchaser: purchaser/index.md
    - Tokenomics: tokenomics/index.md