site_name: Evernode
docs_dir: src
site_dir: docs
theme:
  name: cosmo
extra_css:     
  - css/extra.css
nav:
    - Evers: evers/index.md
    - Registry: registry/index.md
    - Hosts: hosts/index.md
    - Tenants: tenants/index.md
    - more:
      - Anchor tenant: anchor-tenant/index.md
      - Sashimono: hosts/sashimono.md
      - HotPocket: hotpocket/index.md